job
| extend geohash=geo_point_to_geohash(todouble(job.['long']), todouble(job.lat),6), speed=todouble(job.speed)
| order by speed desc
| take 10000
| join kind=leftouter (
    job
    | where job_name == "Diag%startDeviceVin"
    | extend vin = tostring(job.vin)
) on $left.serno == $right.serno
| project geohash, serno, speed, vin
| summarize speed=avg(speed) by geohash, serno
| extend geojson=geo_geohash_to_central_point(geohash)
| top 5 by speed asc;